// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID                  uuid.UUID        `json:"id"`
	Name                string           `json:"name"`
	Description         pgtype.Text      `json:"description"`
	WebsiteUrl          pgtype.Text      `json:"website_url"`
	Industry            pgtype.Text      `json:"industry"`
	TeamSize            pgtype.Text      `json:"team_size"`
	PrimaryCustomerType pgtype.Text      `json:"primary_customer_type"`
	PrimaryUseCase      string           `json:"primary_use_case"`
	OwnerRole           string           `json:"owner_role"`
	ReferralSource      pgtype.Text      `json:"referral_source"`
	IsActive            pgtype.Bool      `json:"is_active"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID        `json:"id"`
	FirstName      string           `json:"first_name"`
	LastName       string           `json:"last_name"`
	Email          string           `json:"email"`
	Password       string           `json:"password"`
	Phone          string           `json:"phone"`
	Role           string           `json:"role"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	OrganizationID pgtype.UUID      `json:"organization_id"`
}
