// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
  name,
  description,
  website_url,
  industry,
  team_size,
  primary_customer_type,
  primary_use_case,
  owner_role,
  referral_source,
  is_active
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
) RETURNING id, name, description, website_url, industry, team_size, primary_customer_type, primary_use_case, owner_role, referral_source, is_active, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name                string      `json:"name"`
	Description         pgtype.Text `json:"description"`
	WebsiteUrl          pgtype.Text `json:"website_url"`
	Industry            pgtype.Text `json:"industry"`
	TeamSize            pgtype.Text `json:"team_size"`
	PrimaryCustomerType pgtype.Text `json:"primary_customer_type"`
	PrimaryUseCase      string      `json:"primary_use_case"`
	OwnerRole           string      `json:"owner_role"`
	ReferralSource      pgtype.Text `json:"referral_source"`
	IsActive            pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Description,
		arg.WebsiteUrl,
		arg.Industry,
		arg.TeamSize,
		arg.PrimaryCustomerType,
		arg.PrimaryUseCase,
		arg.OwnerRole,
		arg.ReferralSource,
		arg.IsActive,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WebsiteUrl,
		&i.Industry,
		&i.TeamSize,
		&i.PrimaryCustomerType,
		&i.PrimaryUseCase,
		&i.OwnerRole,
		&i.ReferralSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  first_name,
  last_name,
  email,
  password,
  phone,
  role,
  avatar_url
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
) RETURNING id, first_name, last_name, email, password, phone, role, avatar_url, created_at, updated_at, organization_id
`

type CreateUserParams struct {
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	Phone     string      `json:"phone"`
	Role      string      `json:"role"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Role,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :one
DELETE FROM organizations WHERE id = $1 RETURNING id, name, description, website_url, industry, team_size, primary_customer_type, primary_use_case, owner_role, referral_source, is_active, created_at, updated_at
`

func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, deleteOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WebsiteUrl,
		&i.Industry,
		&i.TeamSize,
		&i.PrimaryCustomerType,
		&i.PrimaryUseCase,
		&i.OwnerRole,
		&i.ReferralSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users WHERE id = $1 RETURNING id, first_name, last_name, email, password, phone, role, avatar_url, created_at, updated_at, organization_id
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const findAllOrganizations = `-- name: FindAllOrganizations :many
SELECT id, name, description, website_url, industry, team_size, primary_customer_type, primary_use_case, owner_role, referral_source, is_active, created_at, updated_at FROM organizations
`

func (q *Queries) FindAllOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, findAllOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WebsiteUrl,
			&i.Industry,
			&i.TeamSize,
			&i.PrimaryCustomerType,
			&i.PrimaryUseCase,
			&i.OwnerRole,
			&i.ReferralSource,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrganizationByID = `-- name: FindOrganizationByID :one
SELECT id, name, description, website_url, industry, team_size, primary_customer_type, primary_use_case, owner_role, referral_source, is_active, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) FindOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, findOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WebsiteUrl,
		&i.Industry,
		&i.TeamSize,
		&i.PrimaryCustomerType,
		&i.PrimaryUseCase,
		&i.OwnerRole,
		&i.ReferralSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, password, phone, role, avatar_url, created_at, updated_at, organization_id FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, first_name, last_name, email, password, phone, role, avatar_url, created_at, updated_at, organization_id FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, first_name, last_name, email, password, phone, role, avatar_url, created_at, updated_at, organization_id FROM users
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.Role,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations SET
  name = $2,
  description = $3,
  website_url = $4,
  industry = $5,
  team_size = $6,
  primary_customer_type = $7,
  primary_use_case = $8,
  owner_role = $9,
  referral_source = $10,
  is_active = $11
WHERE id = $1 RETURNING id, name, description, website_url, industry, team_size, primary_customer_type, primary_use_case, owner_role, referral_source, is_active, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID                  uuid.UUID   `json:"id"`
	Name                string      `json:"name"`
	Description         pgtype.Text `json:"description"`
	WebsiteUrl          pgtype.Text `json:"website_url"`
	Industry            pgtype.Text `json:"industry"`
	TeamSize            pgtype.Text `json:"team_size"`
	PrimaryCustomerType pgtype.Text `json:"primary_customer_type"`
	PrimaryUseCase      string      `json:"primary_use_case"`
	OwnerRole           string      `json:"owner_role"`
	ReferralSource      pgtype.Text `json:"referral_source"`
	IsActive            pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.WebsiteUrl,
		arg.Industry,
		arg.TeamSize,
		arg.PrimaryCustomerType,
		arg.PrimaryUseCase,
		arg.OwnerRole,
		arg.ReferralSource,
		arg.IsActive,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.WebsiteUrl,
		&i.Industry,
		&i.TeamSize,
		&i.PrimaryCustomerType,
		&i.PrimaryUseCase,
		&i.OwnerRole,
		&i.ReferralSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  first_name = $2,
  last_name = $3,
  email = $4,
  password = $5,
  phone = $6,
  role = $7,
  avatar_url = $8
WHERE id = $1 RETURNING id, first_name, last_name, email, password, phone, role, avatar_url, created_at, updated_at, organization_id
`

type UpdateUserParams struct {
	ID        uuid.UUID   `json:"id"`
	FirstName string      `json:"first_name"`
	LastName  string      `json:"last_name"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	Phone     string      `json:"phone"`
	Role      string      `json:"role"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Role,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const updateUserOrganization = `-- name: UpdateUserOrganization :exec
UPDATE users SET organization_id = $2 WHERE id = $1
`

type UpdateUserOrganizationParams struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) UpdateUserOrganization(ctx context.Context, arg UpdateUserOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateUserOrganization, arg.ID, arg.OrganizationID)
	return err
}
