// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (User, error)
	FindAllOrganizations(ctx context.Context) ([]Organization, error)
	FindOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserOrganization(ctx context.Context, arg UpdateUserOrganizationParams) error
}

var _ Querier = (*Queries)(nil)
